/* --move-catalog: the UNIFIED MOVE MAP (user 2026-08-24) — walk every
 * stock wrestler's ws_move_map row and emit one catalog of every routed
 * move: who uses it, in which category (situation), on which button.
 * The union is the SAFE pick-list for the build-a-wrestler UI (every id
 * in it is proven routable by stock; ids outside it can hit the
 * FF00-hold freeze).
 *
 *   wfengine --move-catalog data/movecatalog.json
 *
 * Reads through the engine's own table layer (move_map_ptrs 0xE4FE,
 * rows 0xE52E: [cat 0..0x14][col B1/B2/both] -> move id, 0xFF = none).
 * Category labels from the selector chain 0xDF3A (core.c):
 * 1/2 = running attack (0xE070), 3/4 = vs running opponent (0xE30C),
 * 0xA-0xD = grapple throws (0xE20E), 0xE/0xF = perch dives (0xE27A),
 * 0x11 = weapon swing, 0x13 = tag assist (0xDF96). Names for move ids
 * come from data/move-names.json (hand-authored overlay, merged here
 * when present). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "../src/tbl.h"
#include "../src/json.h"

static const char *cat_label(unsigned c)
{
    switch (c) {
    case 0x00: return "standing strike";
    case 0x01: return "running attack A";
    case 0x02: return "running attack B";
    case 0x03: return "vs running opponent A";
    case 0x04: return "vs running opponent B";
    case 0x05: return "opponent downed (head)";
    case 0x06: return "opponent downed (feet)";
    case 0x07: return "opponent seated/rising";
    case 0x08: return "rear grapple";
    case 0x09: return "corner/buckle";
    case 0x0A: return "grapple throw (band 0)";
    case 0x0B: return "grapple throw (band 1)";
    case 0x0C: return "grapple throw (band 2)";
    case 0x0D: return "grapple throw (special)";
    case 0x0E: return "perch dive (standing foe)";
    case 0x0F: return "perch dive (downed foe)";
    case 0x10: return "apron";
    case 0x11: return "weapon swing";
    case 0x12: return "ringside";
    case 0x13: return "tag assist";
    case 0x14: return "reserve 0x14";
    default:   return "?";
    }
}

int tool_move_catalog(const char *out)
{
    static const char *ws[12] = { "HULK HOGAN", "ULTIMATE WARRIOR",
        "JAKE ROBERTS", "BIG BOSS MAN", "LOD HAWK", "LOD ANIMAL",
        "SGT SLAUGHTER", "MR PERFECT", "EARTHQUAKE", "TED DIBIASE",
        "DEMOLITION SMASH", "DEMOLITION CRUSH" };
    static const char *cols[3] = { "B1", "B2", "B1+B2" };
    /* users[move][k] packed: wrestler | cat<<8 | col<<16 */
    static uint32_t users[256][96];
    static int nuse[256];
    json_val *names = NULL;
    char err[128];
    FILE *f;

    {   /* optional hand-authored names overlay */
        names = json_parse_file("data/move-names.json", err, sizeof err);
    }

    for (unsigned id = 0; id < 12; id++) {
        uint32_t map = tbl32(tbl_id("move_map_ptrs"), id * 4u);
        for (unsigned cat = 0; cat <= 0x14; cat++)
            for (unsigned col = 0; col < 3; col++) {
                uint8_t mv = tbl_ra8(map + cat * 3u + col);
                if (mv == 0xFFu) continue;
                if (nuse[mv] < 96)
                    users[mv][nuse[mv]++] = id | (cat << 8) | (col << 16);
            }
    }

    f = fopen(out, "w");
    if (!f) { fprintf(stderr, "move-catalog: cannot write %s\n", out); return 1; }
    fprintf(f, "{\n\"note\": \"unified move map: every move id routed by any stock wrestler (the SAFE pick list). GENERATED by wfengine --move-catalog; names merge from data/move-names.json.\",\n");
    fprintf(f, "\"categories\": {");
    for (unsigned c = 0; c <= 0x14; c++)
        fprintf(f, "%s\n  \"%u\": \"%s\"", c ? "," : "", c, cat_label(c));
    fprintf(f, "\n},\n\"moves\": {");
    {
        int first = 1, total = 0;
        for (unsigned mv = 0; mv < 256; mv++) {
            const char *nm = NULL;
            if (!nuse[mv]) continue;
            if (names) {
                char key[8]; snprintf(key, sizeof key, "%u", mv);
                nm = json_str(json_get(names, key), NULL);
            }
            fprintf(f, "%s\n  \"%u\": { ", first ? "" : ",", mv);
            first = 0; total++;
            if (nm) { fprintf(f, "\"name\": "); json_write_string(f, nm); fprintf(f, ", "); }
            fprintf(f, "\"users\": [");
            for (int k = 0; k < nuse[mv]; k++) {
                unsigned u = users[mv][k];
                fprintf(f, "%s{\"w\":%u,\"who\":\"%s\",\"cat\":%u,\"col\":\"%s\"}",
                        k ? "," : "", u & 0xFFu, ws[u & 0xFFu],
                        (u >> 8) & 0xFFu, cols[(u >> 16) & 3u]);
            }
            fprintf(f, "] }");
        }
        fprintf(f, "\n},\n\"maps\": {");
        for (unsigned id = 0; id < 12; id++) {
            uint32_t map = tbl32(tbl_id("move_map_ptrs"), id * 4u);
            fprintf(f, "%s\n  \"%u\": [", id ? "," : "", id);
            for (unsigned cat = 0; cat <= 0x14; cat++) {
                fprintf(f, "%s[", cat ? "," : "");
                for (unsigned col = 0; col < 3; col++)
                    fprintf(f, "%s%u", col ? "," : "", tbl_ra8(map + cat * 3u + col));
                fprintf(f, "]");
            }
            fprintf(f, "]");
        }
        fprintf(f, "\n}\n}\n");
        fclose(f);
        fprintf(stderr, "move-catalog: %d distinct moves -> %s\n", total, out);
    }
    if (names) json_free(names);
    return 0;
}
